Convert urllib.ParseResult to str when raising QuarkError
Without this, we'll get the following error when raising QuarkError:

    File "../quark/bin/../quark/subproject.py", line 842, in _parse_url
        raise QuarkError("Missing job fragment in URL: " + url)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
    TypeError: can only concatenate str (not "ParseResult") to str